name: streamhub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1
  http: ^0.12.0+4
  flare_splash_screen: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/logos/nba.jpg
    - assets/images/logos/football.jpg
    - assets/flare/Loading.flr
    - assets/images/balls/football.jpg
    - assets/images/balls/basketball.jpg

  fonts:
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
          weight: 500